sudo: required
services: 
  - docker

before_install:
  - docker build -t roigtoni94/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true roigtoni94/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  dpl_version: 1.10.16
  region: "eu-north-1"
  app: "frontend"
  environment: "frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-084828562722"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
